export const CLEAR_SEASONS_LIST = 'CLEAR_VENUES_LIST';

export const GET_ALL_SEASONS_START = 'GET_ALL_SEASONS_START';
export const GET_ALL_SEASONS_SUCCESS = 'GET_ALL_SEASONS_SUCCESS';
export const GET_ALL_SEASONS_ERROR = 'GET_ALL_SEASONS_ERROR';

export const GET_SEASONS_RANGE_START = 'GET_SEASONS_RANGE_START';
export const GET_SEASONS_RANGE_SUCCESS = 'GET_SEASONS_RANGE_SUCCESS';
export const GET_SEASONS_RANGE_ERROR = 'GET_SEASONS_RANGE__ERROR';

export const GET_SEASON_BY_ID_START = 'GET_SEASON_BY_ID_START';
export const GET_SEASON_BY_ID_SUCCESS = 'GET_SEASON_BY_ID_SUCCESS';
export const GET_SEASON_BY_ID_ERROR = 'GET_SEASON_BY_ID_ERROR';
