export const BOOKMARKS_ADD_FRANCHISE = 'BOOKMARKS_ADD_FRANCHISE';
export const BOOKMARKS_DELETE_FRANCHISE = 'BOOKMARKS_DELETE_FRANCHISE';
export const BOOKMARKS_DELETE_ALL_FRANCHISE = 'BOOKMARKS_DELETE_ALL_FRANCHISE';

export const BOOKMARKS_ADD_PERSON = 'BOOKMARKS_ADD_PERSON';
export const BOOKMARKS_DELETE_PERSON = 'BOOKMARKS_DELETE_PERSON';
export const BOOKMARKS_DELETE_ALL_PEOPLE = 'BOOKMARKS_DELETE_ALL_PEOPLE';
