export const CLEAR_VENUES_LIST = 'CLEAR_VENUES_LIST';

export const GET_ALL_VENUES_START = 'GET_ALL_VENUES_START';
export const GET_ALL_VENUES_SUCCESS = 'GET_ALL_VENUES_SUCCESS';
export const GET_ALL_VENUESS_ERROR = 'GET_ALL_VENUES_ERROR';

export const GET_VENUES_RANGE_START = 'GET_VENUES_RANGE_START';
export const GET_VENUES_RANGE_SUCCESS = 'GET_VENUES_RANGE_SUCCESS';
export const GET_VENUES_RANGE_ERROR = 'GET_VENUES_RANGE_ERROR';

export const GET_VENUE_BY_ID_START = 'GET_VENUE_BY_ID_START';
export const GET_VENUE_BY_ID_SUCCESS = 'GET_VENUE_BY_ID_SUCCESS';
export const GET_VENUE_BY_ID_ERROR = 'GET_VENUE_BY_ID_ERROR';
