export const CLEAR_LOCATIONS_LIST = 'CLEAR_LOCATIONS_LIST';

export const GET_ALL_LOCATIONS_START = 'GET_ALL_LOCATIONS_START';
export const GET_ALL_LOCATIONS_SUCCESS = 'GET_ALL_LOCATIONS_SUCCESS';
export const GET_ALL_LOCATIONS_ERROR = 'GET_ALL_LOCATIONS_ERROR';

export const GET_LOCATIONS_RANGE_START = 'GET_LOCATIONS_RANGE_START';
export const GET_LOCATIONS_RANGE_SUCCESS = 'GET_LOCATIONS_RANGE_SUCCESS';
export const GET_LOCATIONS_RANGE_ERROR = 'GET_LOCATIONS_RANGE_ERROR';

export const GET_LOCATION_BY_ID_START = 'GET_LOCATION_BY_ID_START';
export const GET_LOCATION_BY_ID_SUCCESS = 'GET_LOCATION_BY_ID_SUCCESS';
export const GET_LOCATION_BY_ID_ERROR = 'GET_LOCATION_BY_ID_ERROR';

export const POST_NEW_LOCATION = 'POST_NEW_LOCATION';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const DELETE_LOCATION = 'DELETE_LOCATION';
